#!/usr/bin/python3
__author__ = "David COBAC"
__date__ = 20191230

import motd
import json
import argparse


parseur_args = argparse.ArgumentParser(
    description="""Mathematicians Of The Day from website
    http://mathshistory.st-andrews.ac.uk/Day_files/Year.html
    not an official package""")

parseur_args.add_argument('-d', '--date', help='JJ/MM')
parseur_args.add_argument('decalage',
                          nargs='?',
                          default='+0')

args = parseur_args.parse_args()

m = motd.motd(args.date, args.decalage)
dico = json.loads(m.sortie())
for k in dico:
    # print(k)
    for entree in dico[k]:
        s = str(entree['annee'])
        s += " "
        s += entree['type']
        s += " "
        s += entree['prenom']
        s += " "
        s += entree['nom']
        #
        print(s)
